-- AnimeRank v0.3 – Supabase schema
-- Run this whole file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Anime-Fan',
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  invite_code text not null unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','member')),
  joined_at timestamptz not null default now(),
  primary key (group_id,user_id)
);

create table if not exists public.anime (
  id bigint generated by default as identity primary key,
  anilist_id integer not null unique,
  title text not null,
  cover text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_anime (
  group_id uuid not null references public.groups(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  added_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id,anime_id)
);

create table if not exists public.ratings (
  group_id uuid not null references public.groups(id) on delete cascade,
  anime_id bigint not null references public.anime(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer check (score between 1 and 6),
  seen boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (group_id,anime_id,user_id)
);

create index if not exists group_members_user_idx on public.group_members(user_id);
create index if not exists group_anime_group_idx on public.group_anime(group_id);
create index if not exists ratings_group_anime_idx on public.ratings(group_id,anime_id);

create or replace function public.is_group_member(p_group_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(select 1 from public.group_members where group_id=p_group_id and user_id=auth.uid());
$$;

create or replace function public.is_group_owner(p_group_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(select 1 from public.groups where id=p_group_id and owner_id=auth.uid());
$$;

create or replace function public.make_invite_code()
returns text language plpgsql security definer set search_path=public
as $$
declare c text; ok boolean;
begin
  loop
    c := 'ANIME-' || upper(substr(encode(gen_random_bytes(4),'hex'),1,4));
    select not exists(select 1 from public.groups where invite_code=c) into ok;
    exit when ok;
  end loop;
  return c;
end; $$;

create or replace function public.create_animerank_group(p_name text)
returns public.groups
language plpgsql security definer set search_path=public
as $$
declare g public.groups;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  insert into public.groups(name,invite_code,owner_id) values(trim(coalesce(p_name,'Meine Anime-Gruppe')),public.make_invite_code(),auth.uid()) returning * into g;
  insert into public.group_members(group_id,user_id,role) values(g.id,auth.uid(),'owner');
  return g;
end; $$;

create or replace function public.join_animerank_group(p_code text)
returns public.groups
language plpgsql security definer set search_path=public
as $$
declare g public.groups;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  select * into g from public.groups where upper(invite_code)=upper(trim(p_code));
  if g.id is null then raise exception 'Ungültiger Einladungscode'; end if;
  insert into public.group_members(group_id,user_id,role) values(g.id,auth.uid(),'member') on conflict do nothing;
  return g;
end; $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,username) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1))) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.anime enable row level security;
alter table public.group_anime enable row level security;
alter table public.ratings enable row level security;

revoke all on public.profiles,public.groups,public.group_members,public.anime,public.group_anime,public.ratings from anon;
grant select,insert,update on public.profiles to authenticated;
grant select,update on public.groups to authenticated;
grant select on public.group_members to authenticated;
grant select,insert,update on public.anime to authenticated;
grant select,insert,delete on public.group_anime to authenticated;
grant select,insert,update,delete on public.ratings to authenticated;
grant execute on function public.create_animerank_group(text) to authenticated;
grant execute on function public.join_animerank_group(text) to authenticated;

-- Policies
 drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for all to authenticated using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists groups_member_read on public.groups;
create policy groups_member_read on public.groups for select to authenticated using (public.is_group_member(id));
drop policy if exists groups_owner_update on public.groups;
create policy groups_owner_update on public.groups for update to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid());

drop policy if exists members_read on public.group_members;
create policy members_read on public.group_members for select to authenticated using (public.is_group_member(group_id));

drop policy if exists anime_read on public.anime;
create policy anime_read on public.anime for select to authenticated using (exists(select 1 from public.group_anime ga where ga.anime_id=id and public.is_group_member(ga.group_id)));
drop policy if exists anime_insert on public.anime;
create policy anime_insert on public.anime for insert to authenticated with check (true);

drop policy if exists group_anime_member_read on public.group_anime;
create policy group_anime_member_read on public.group_anime for select to authenticated using (public.is_group_member(group_id));
drop policy if exists group_anime_member_insert on public.group_anime;
create policy group_anime_member_insert on public.group_anime for insert to authenticated with check (public.is_group_member(group_id) and added_by=auth.uid());
drop policy if exists group_anime_owner_delete on public.group_anime;
create policy group_anime_owner_delete on public.group_anime for delete to authenticated using (public.is_group_member(group_id));

drop policy if exists ratings_member_read on public.ratings;
create policy ratings_member_read on public.ratings for select to authenticated using (public.is_group_member(group_id));
drop policy if exists ratings_member_insert on public.ratings;
create policy ratings_member_insert on public.ratings for insert to authenticated with check (public.is_group_member(group_id) and user_id=auth.uid());
drop policy if exists ratings_member_update on public.ratings;
create policy ratings_member_update on public.ratings for update to authenticated using (public.is_group_member(group_id) and user_id=auth.uid()) with check (public.is_group_member(group_id) and user_id=auth.uid());
drop policy if exists ratings_member_delete on public.ratings;
create policy ratings_member_delete on public.ratings for delete to authenticated using (public.is_group_member(group_id) and user_id=auth.uid());

-- Keep these functions executable only by authenticated users.
revoke all on function public.make_invite_code() from public;
revoke all on function public.is_group_member(uuid) from public;
revoke all on function public.is_group_owner(uuid) from public;
grant execute on function public.is_group_member(uuid) to authenticated;
grant execute on function public.is_group_owner(uuid) to authenticated;
